name: Build Android

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: reactnativecommunity/react-native-android

    strategy:
      matrix:
        security_level: [none, library, proxy-bypass, custom, frida-resistant]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Merge environment files
        run: cat .env .env.${{ matrix.security_level }} > .env.build

      - name: Build Android APK
        env:
          SECURITY_LEVEL: ${{ matrix.security_level }}
        run: |
          cd android
          ./gradlew assembleRelease --console=plain

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.security_level }}-release
          path: android/app/build/outputs/apk/release/app-release.apk
